'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { execute, verifyBuild } = require('./harness');
const { openStore, hash } = require('./storage');
const { encodeWav } = require('./engine');
const root = fs.mkdtempSync(path.join(os.tmpdir(), 'ashfox-harness-test-'));
const run = (r) => execute(root, r);
try {
  const source = fs.readFileSync(path.join(__dirname, '../../examples/sounds/src/bird_call.ashfox'), 'utf8');
  const files = { 'sounds/bird_call.ashfox': source };
  assert.equal(run({ op: 'inspect' }).head, null);
  const initial = run({ op: 'init', files });
  assert.throws(() => run({ op: 'init', files }), /already initialized/);
  assert.deepEqual(run({ op: 'inspect' }).files, files);
  assert.throws(() => run({ op: 'inspect', ignored: true }), /Expected exactly/);
  const edit = source.replace(/hz = [0-9]+/, 'hz = 1800');
  assert.notEqual(edit, source, 'Pitch edit must change the source');
  const candidate = run({ op: 'propose', expectedHead: initial.id, writes: { 'sounds/bird_call.ashfox': edit }, deletes: [] });
  assert.deepEqual(run({ op: 'inspect' }).head, initial, 'Propose mutates head');
  assert.throws(() => run({ op: 'propose', expectedHead: '0'.repeat(64), writes: {}, deletes: [] }), /current source/);
  assert.throws(() => run({ op: 'propose', expectedHead: initial.id, writes: { '../escape.json': source }, deletes: [] }), /path/);
  assert.throws(() => run({ op: 'propose', expectedHead: initial.id, writes: {}, deletes: ['missing'] }), /Delete/);
  const bad = source.replace(/rmsDb = -?[0-9]+/, 'rmsDb = 100');
  assert.throws(() => run({ op: 'propose', expectedHead: initial.id, writes: { 'sounds/bird_call.ashfox': bad }, deletes: [] }), /expected/);
  assert.deepEqual(run({ op: 'inspect' }).head, initial, 'Invalid input mutates head');
  // A real PCM fixture isolates state transitions from the optional encoder installation.
  const bytes = Buffer.from(encodeWav(new Float64Array([0, .1, -.1, 0])));
  const receipt = { sourceHash: candidate.source, entries: [{ sound: 'bird_call', variant: 'base', wav: 'bird_call/base.wav', ogg: 'bird_call/base.ogg', wavHash: hash(bytes), oggHash: hash(bytes) }] };
  const build = hash(receipt), dir = path.join(root, 'builds', build);
  fs.mkdirSync(path.join(dir, 'bird_call'), { recursive: true });
  fs.writeFileSync(path.join(dir, 'receipt.json'), JSON.stringify(receipt));
  fs.writeFileSync(path.join(dir, 'bird_call/base.wav'), bytes); fs.writeFileSync(path.join(dir, 'bird_call/base.ogg'), bytes);
  assert.throws(() => run({ op: 'review' }), /Unknown operation/);
  assert.throws(() => run({ op: 'adopt' }), /Unknown operation/);
  run({ op: 'present', candidate: candidate.candidate, build });
  assert.deepEqual(run({ op: 'inspect' }).head, initial);
  assert.throws(() => run({ op: 'apply', expectedHead: '0'.repeat(64), candidate: candidate.candidate, build }), /stale/);
  const head = run({ op: 'apply', expectedHead: initial.id, candidate: candidate.candidate, build });
  assert.notEqual(head.id, initial.id);
  assert.equal(head.source, candidate.source);
  assert.throws(() => run({ op: 'apply', expectedHead: initial.id, candidate: candidate.candidate, build }), /stale/);
  const exported = run({ op: 'export', head: head.id, build, target: 'audio-bundle' });
  assert.deepEqual(fs.readFileSync(path.join(exported.directory, 'bird_call/base.wav')), bytes);
  assert.throws(() => run({ op: 'export', head: initial.id, build, target: 'audio-bundle' }), /applied/);
  assert.equal(fs.readFileSync(path.join(exported.directory, 'source/sounds/bird_call.ashfox'), 'utf8'), edit);
  fs.writeFileSync(path.join(dir, 'bird_call/base.wav'), 'corrupt');
  assert.throws(() => verifyBuild(openStore(root), build), /mismatch/);
  assert.throws(() => run({ op: 'export', head: head.id, build, target: 'audio-bundle' }), /mismatch/);
  assert.deepEqual(openStore(root).head(), head, 'Failed export mutates head');
  console.log('Harness state: closed inputs, source inventory, candidate isolation, stale heads, presentation, application, exact export and corruption rejection passed.');
} finally { fs.rmSync(root, { recursive: true, force: true }); }
