import {
  MODEL_SPEC_ANCHOR_BONE_ID_INVALID,
  MODEL_SPEC_ANCHOR_CUBE_ID_INVALID,
  MODEL_SPEC_ANCHOR_ID_DUPLICATE,
  MODEL_SPEC_ANCHOR_ID_REQUIRED,
  MODEL_SPEC_ANCHOR_NOT_FOUND,
  MODEL_SPEC_ANCHOR_OBJECT,
  MODEL_SPEC_ANCHOR_OFFSET_INVALID,
  MODEL_SPEC_ANCHOR_REF_STRING,
  MODEL_SPEC_ANCHOR_REQUIRED,
  MODEL_SPEC_ANCHOR_TARGET_INVALID,
  MODEL_SPEC_ANCHORS_ARRAY,
  MODEL_SPEC_BONE_OBJECT,
  MODEL_SPEC_CONTENT_REQUIRED,
  MODEL_SPEC_CUBE_OBJECT,
  MODEL_SPEC_REQUIRED
} from '../messages';

export const buildModelSpecMessages = () => ({
  modelRequired: MODEL_SPEC_REQUIRED,
  modelContentRequired: MODEL_SPEC_CONTENT_REQUIRED,
  anchorsArray: MODEL_SPEC_ANCHORS_ARRAY,
  boneObject: MODEL_SPEC_BONE_OBJECT,
  cubeObject: MODEL_SPEC_CUBE_OBJECT,
  anchorObject: MODEL_SPEC_ANCHOR_OBJECT,
  anchorIdRequired: MODEL_SPEC_ANCHOR_ID_REQUIRED,
  anchorIdDuplicate: MODEL_SPEC_ANCHOR_ID_DUPLICATE,
  anchorTargetInvalid: MODEL_SPEC_ANCHOR_TARGET_INVALID,
  anchorBoneIdInvalid: MODEL_SPEC_ANCHOR_BONE_ID_INVALID,
  anchorCubeIdInvalid: MODEL_SPEC_ANCHOR_CUBE_ID_INVALID,
  anchorOffsetInvalid: MODEL_SPEC_ANCHOR_OFFSET_INVALID,
  anchorRefString: MODEL_SPEC_ANCHOR_REF_STRING,
  anchorRequired: MODEL_SPEC_ANCHOR_REQUIRED,
  anchorNotFound: MODEL_SPEC_ANCHOR_NOT_FOUND
});
