import {
  TEXTURE_DETECT_NO_CHANGE_REQUIRES_EXISTING,
  TEXTURE_DIMENSION_POSITIVE,
  TEXTURE_OP_INVALID,
  TEXTURE_OPS_TOO_MANY,
  TEXTURE_SPEC_DETECT_NO_CHANGE_UPDATE_ONLY,
  TEXTURE_SPECS_REQUIRED,
  TEXTURE_SPEC_MODE_UNSUPPORTED,
  TEXTURE_SPEC_NAME_REQUIRED,
  TEXTURE_SPEC_TARGET_REQUIRED,
  TEXTURE_SIZE_EXCEEDS_MAX
} from '../messages';
import { buildUvPaintMessages } from './uv';

export const buildTextureSpecSizeMessages = () => ({
  dimensionPositive: TEXTURE_DIMENSION_POSITIVE
});

export const buildTextureSpecMessages = () => ({
  specsRequired: TEXTURE_SPECS_REQUIRED,
  modeUnsupported: TEXTURE_SPEC_MODE_UNSUPPORTED,
  nameRequired: TEXTURE_SPEC_NAME_REQUIRED,
  targetRequired: TEXTURE_SPEC_TARGET_REQUIRED,
  dimensionPositive: TEXTURE_DIMENSION_POSITIVE,
  sizeExceedsMax: TEXTURE_SIZE_EXCEEDS_MAX,
  opsTooMany: TEXTURE_OPS_TOO_MANY,
  opInvalid: TEXTURE_OP_INVALID,
  detectNoChangeRequiresExisting: TEXTURE_DETECT_NO_CHANGE_REQUIRES_EXISTING,
  detectNoChangeUpdateOnly: TEXTURE_SPEC_DETECT_NO_CHANGE_UPDATE_ONLY,
  uvPaint: buildUvPaintMessages()
});
