import {
  VALIDATION_ANIMATION_TOO_LONG,
  VALIDATION_CUBE_CONTAINMENT,
  VALIDATION_DUPLICATE_BONE,
  VALIDATION_DUPLICATE_CUBE,
  VALIDATION_FACE_UV_OUT_OF_BOUNDS,
  VALIDATION_MAX_CUBES_EXCEEDED,
  VALIDATION_NO_BONES,
  VALIDATION_ORPHAN_CUBE,
  VALIDATION_TEXTURE_SIZE_MISMATCH,
  VALIDATION_TEXTURE_TOO_LARGE,
  VALIDATION_TEXTURE_UNASSIGNED,
  VALIDATION_TEXTURE_UNRESOLVED_REFS,
  VALIDATION_UV_OUT_OF_BOUNDS,
  VALIDATION_UV_OVERLAP,
  VALIDATION_UV_SCALE_MISMATCH,
  VALIDATION_UV_SCALE_MISMATCH_SUMMARY
} from '../messages';

export const buildValidationMessages = () => ({
  noBones: VALIDATION_NO_BONES,
  orphanCube: VALIDATION_ORPHAN_CUBE,
  duplicateBone: VALIDATION_DUPLICATE_BONE,
  duplicateCube: VALIDATION_DUPLICATE_CUBE,
  cubeContainment: VALIDATION_CUBE_CONTAINMENT,
  maxCubesExceeded: VALIDATION_MAX_CUBES_EXCEEDED,
  animationTooLong: VALIDATION_ANIMATION_TOO_LONG,
  textureTooLarge: VALIDATION_TEXTURE_TOO_LARGE,
  textureSizeMismatch: VALIDATION_TEXTURE_SIZE_MISMATCH,
  uvOutOfBounds: VALIDATION_UV_OUT_OF_BOUNDS,
  textureUnresolvedRefs: VALIDATION_TEXTURE_UNRESOLVED_REFS,
  textureUnassigned: VALIDATION_TEXTURE_UNASSIGNED,
  faceUvOutOfBounds: VALIDATION_FACE_UV_OUT_OF_BOUNDS,
  uvOverlap: VALIDATION_UV_OVERLAP,
  uvScaleMismatch: VALIDATION_UV_SCALE_MISMATCH,
  uvScaleMismatchSummary: VALIDATION_UV_SCALE_MISMATCH_SUMMARY
});
