export const TRANSPORT_MAX_PAYLOAD_BYTES = 5_000_000;
export const MCP_HTTP_MAX_HEADER_BYTES = 16 * 1024;
export const TRANSPORT_REQUEST_TIMEOUT_MS = 30_000;
export const MCP_MAX_TRANSPORT_CONNECTIONS = 512;
export const MCP_MAX_SESSIONS = 1_024;
export const MCP_MAX_SSE_CONNECTIONS = 256;
export const MCP_MAX_SSE_CONNECTIONS_PER_SESSION = 3;
