import assert from 'node:assert/strict';
import { readRecipe, type Curve } from '../../src';
import { evaluate } from '../../src/curve';
import { fixture } from './fixture';
const c: Curve = { domain: 'log', interpolation: 'linear', points: [{ at: 0, value: 100 }, { at: 1, value: 400 }] };
assert.equal(evaluate(c, 0), 100); assert.equal(evaluate(c, 1), 400); assert.ok(Math.abs(evaluate(c, .5) - 200) < 1e-10);
const smooth: Curve = { ...c, domain: 'linear', interpolation: 'smooth' };
assert.ok((evaluate(smooth, .000001) - 100) / .000001 < .001);
for (let i = 0; i <= 100; i++) assert.ok(evaluate(smooth, i / 100) >= 100 && evaluate(smooth, i / 100) <= 400);
const r = fixture(), voice = r.voices[0];
for (const points of [[{ at: 0, value: 0 }, { at: 1, value: 1 }], [{ at: 0, value: 100 }, { at: 0, value: 200 }]]) assert.throws(() => readRecipe({ ...r, voices: [{ ...voice, lowpass: { ...c, points } }] }));
assert.throws(() => readRecipe({ ...r, voices: [{ ...voice, highpass: 500, lowpass: c }] }), /separate the entire/);
assert.throws(() => readRecipe({ ...r, voices: [{ ...voice, gain: { ...smooth, points: [{ at: 0, value: 0 }, { at: .001, value: 1 }, { at: 1, value: 0 }] } }] }), /96 frames/);
assert.throws(() => readRecipe({ ...r, voices: [{ ...voice, gain: 1 }] }), /zero endpoint/);
assert.throws(() => readRecipe({ ...r, voices: [{ ...voice, gain: { ...smooth, domain: 'log' } }] }), /domain/);
process.stdout.write('curve: endpoint/midpoint, smooth slopes, positive log, no overshoot, cutoff invariant and shortest resolution passed\n');
