import type {
  MinecraftJavaBlockFormatProfile,
  ProjectDocument
} from '../../../model';

const MODERN_RESOURCE_PACK_FORMAT_MINIMUM = 65;

export interface MinecraftJavaBlockState {
  variants: {
    '': {
      model: string;
    };
  };
}

interface MinecraftJavaPackFormatMetadata {
  pack: {
    pack_format: number;
    supported_formats: number;
    description: string;
  };
}

interface MinecraftJavaFormatRangeMetadata {
  pack: {
    min_format: readonly [number, 0];
    max_format: readonly [number, 0];
    description: string;
  };
}

export type MinecraftJavaPackMetadata =
  | MinecraftJavaPackFormatMetadata
  | MinecraftJavaFormatRangeMetadata;

const javaProfile = (
  document: ProjectDocument
): MinecraftJavaBlockFormatProfile => {
  const profile = document.formatProfile;
  if (profile.id !== 'minecraft.java_block') {
    throw new Error(
      'Project does not use the minecraft.java_block profile.'
    );
  }
  return profile;
};

export const buildMinecraftJavaBlockState = (
  document: ProjectDocument
): MinecraftJavaBlockState => {
  const profile = javaProfile(document);
  return {
    variants: {
      '': {
        model:
          `${profile.namespace}:block/${profile.modelPath}`
      }
    }
  };
};

export const buildMinecraftJavaPackMetadata = (
  document: ProjectDocument
): MinecraftJavaPackMetadata => {
  const profile = javaProfile(document);
  const description = `${document.name} · generated by ashfox`;
  const format: number = profile.resourcePackFormat;
  if (format < MODERN_RESOURCE_PACK_FORMAT_MINIMUM) {
    return {
      pack: {
        pack_format: format,
        supported_formats: format,
        description
      }
    };
  }
  return {
    pack: {
      min_format: [format, 0],
      max_format: [format, 0],
      description
    }
  };
};
