'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');const path=require('node:path');const os=require('node:os');
const {spawnSync,spawn}=require('node:child_process');const {unzipSync}=require('fflate');
const root=path.resolve(__dirname,'../..'),cli=path.join(__dirname,'dist/ashfox.cjs');
const temp=fs.mkdtempSync(path.join(os.tmpdir(),'ashfox-observe-test-'));
const source=fs.readFileSync(path.join(root,'examples/items/src/iron_sword.ashfox'),'utf8');
const shared=fs.readFileSync(path.join(root,'examples/items/src/shared.ashfox'),'utf8');
const input={source,name:'iron_sword.ashfox',files:{'shared.ashfox':shared}};
const run=(args,stdin)=>spawnSync(process.execPath,[cli,...args],{cwd:temp,input:stdin,timeout:120000,maxBuffer:64*1024*1024});
const success=reply=>{assert.equal(reply.status,0,String(reply.stderr));return reply.stdout;};
async function main(){
  const inspected=JSON.parse(success(run(['inspect','--input-json'],JSON.stringify(input))));assert.equal(inspected.kind,'sprite');
  assert.equal(inspected.receipt.width,16);assert.equal(inspected.evidence.length,256);
  const png=success(run(['export','--input-json'],JSON.stringify(input)));assert.equal(png.subarray(1,4).toString(),'PNG');
  const fromPng=JSON.parse(success(run(['inspect','--stdin','--input-format','png'],png)));assert.equal(fromPng.width,16);
  const bad=run(['capture','--stdin'],'invalid');assert.notEqual(bad.status,0);assert.equal(bad.stdout.length,0);assert.match(bad.stderr.toString(),/error/);
  const ignored=path.join(temp,'.ashfoxworkspace');fs.writeFileSync(ignored,'invalid workspace deliberately ignored');
  fs.copyFileSync(path.join(root,'examples/minecraft/marker.ashfox'),path.join(temp,'marker.ashfox'));
  assert.equal(JSON.parse(success(run(['inspect','marker.ashfox']))).kind,'model');
  const glb=success(run(['export','marker.ashfox']));assert.equal(glb.subarray(0,4).toString(),'glTF');
  const zip=success(run(['export','marker.ashfox','--format','java_block','--namespace','demo']));
  const files=unzipSync(zip);assert.ok(Object.keys(files).some(p=>p.endsWith('marker.json')));
  assert.equal(success(run(['export','marker.ashfox','--output','model.glb'])).length,0);
  const original=fs.readFileSync(path.join(temp,'model.glb'));
  const collision=run(['export','marker.ashfox','--output','model.glb']);assert.notEqual(collision.status,0);assert.deepEqual(fs.readFileSync(path.join(temp,'model.glb')),original);
  const child=spawn(process.execPath,[cli,'stdio'],{cwd:temp,stdio:['pipe','pipe','pipe']});
  let text='',errors='';const waiting=new Map();
  child.stdout.on('data',data=>{text+=data;let end;while((end=text.indexOf('\n'))>=0){const reply=JSON.parse(text.slice(0,end));text=text.slice(end+1);waiting.get(reply.id)?.(reply);waiting.delete(reply.id);}});
  child.stderr.on('data',data=>errors+=data);
  const request=(id,method,params={})=>new Promise(resolve=>{waiting.set(id,resolve);child.stdin.write(JSON.stringify({id,method,params})+'\n');});
  const loaded=await request('load','load',{input});assert.equal(loaded.ok,true);const revision=loaded.result.revision;
  assert.equal((await request('bad','load',{input,expectedRevision:'stale'})).ok,false);
  assert.equal((await request('source','source')).result.revision,revision);
  const invalid={...input,source:'invalid'};
  assert.equal((await request('invalid','load',{input:invalid,expectedRevision:revision})).ok,false);
  assert.equal((await request('inspect','inspect')).result.revision,revision);
  assert.equal((await request('unknown','capture',{options:{fake:true}})).ok,false);
  assert.equal((await request('emptycancel','cancel',{id:'absent'})).result.cancelled,false);
  const compile=request('compiling','load',{input:{file:path.join(root,'examples/fox/creatures/fox.ashfox')},expectedRevision:revision});
  await new Promise(resolve=>setTimeout(resolve,10));
  assert.equal((await request('stopcompile','cancel',{id:'compiling'})).result.cancelled,true);
  assert.equal((await compile).ok,false);
  assert.equal((await request('retained','source')).result.revision,revision);
  const updated=await request('update','load',{input:{...input,source:source+'\n'},expectedRevision:revision});assert.equal(updated.ok,true);assert.notEqual(updated.result.revision,revision);
  assert.equal((await request('close','close')).ok,true);assert.equal((await request('closed','inspect')).ok,false);
  const exit=new Promise(resolve=>child.on('exit',resolve));child.stdin.end();assert.equal(await exit,0);assert.equal(errors,'');
  assert.deepEqual(fs.readdirSync(temp).sort(),['.ashfoxworkspace','marker.ashfox','model.glb']);
  console.log('Observation stdio, source graph, PNG input, exports, no implicit writes, closed options, stale load and failure preservation passed');
}
main().finally(()=>fs.rmSync(temp,{recursive:true,force:true})).catch(error=>{console.error(error);process.exitCode=1;});
