import assert from 'node:assert/strict';
import path from 'node:path';

import type {
  ExportBundle,
  JsonExportFile,
  MinecraftJavaModel,
  ProjectDocument
} from '../src';
import {
  exportMinecraftBedrock
} from '../src/export/targets/bedrock/exporter';
import {
  exportGeckoLib5
} from '../src/export/targets/geckolib5/exporter';
import {
  exportMinecraftJavaBlock
} from '../src/export/targets/javaBlock/exporter';
import {
  createAnimatedBedrockProject,
  createGeckoLib5Project,
  createJavaProject
} from './helpers';

const jsonFileAt = (
  bundle: ExportBundle,
  filePath: string
): JsonExportFile => {
  const file = bundle.files.find((candidate) => candidate.path === filePath);
  assert.equal(file?.kind, 'json', `Expected JSON artifact ${filePath}`);
  if (file?.kind !== 'json') {
    throw new Error(`JSON artifact ${filePath} is missing.`);
  }
  return file;
};

const assertPortableBundle = (bundle: ExportBundle): void => {
  const filePaths = bundle.files.map((file) => file.path);
  assert.equal(
    new Set(filePaths).size,
    filePaths.length,
    'Export paths must be unique.'
  );
  for (const file of bundle.files) {
    assert.equal(file.path, path.posix.normalize(file.path));
    assert.equal(path.posix.isAbsolute(file.path), false);
    assert.equal(file.path.includes('\\'), false);
    assert.equal(
      file.path.split('/').some((segment) => segment === '..'),
      false
    );
    if (file.kind === 'json') {
      assert.deepEqual(
        JSON.parse(file.text),
        file.data,
        `${file.path} must load back to its canonical JSON value.`
      );
    }
  }
  for (const entrypoint of bundle.entrypoints) {
    assert.ok(
      filePaths.includes(entrypoint),
      `Entrypoint ${entrypoint} must identify an exported file.`
    );
  }
};

const assertJavaTextureReferencesResolve = (
  bundle: ExportBundle,
  model: MinecraftJavaModel
): void => {
  const outputPaths = new Set(bundle.files.map((file) => file.path));
  for (const value of Object.values(model.textures)) {
    if (value.startsWith('#')) continue;
    const separator = value.indexOf(':');
    assert.ok(separator > 0, `Texture reference ${value} must be namespaced.`);
    const namespace = value.slice(0, separator);
    const resourcePath = value.slice(separator + 1);
    assert.ok(
      outputPaths.has(`assets/${namespace}/textures/${resourcePath}.png`),
      `Texture reference ${value} must resolve inside the bundle.`
    );
  }
};

{
  const bundle = exportMinecraftJavaBlock(createJavaProject());
  assertPortableBundle(bundle);
  assert.equal(bundle.target.version, '1.21.11');
  assert.equal(bundle.rootPath, 'resource-pack');
  assert.deepEqual(
    bundle.files.map(({ role, path: filePath }) => [role, filePath]),
    [
      ['manifest', 'pack.mcmeta'],
      ['blockstate', 'assets/ashfox/blockstates/ashfox_crate.json'],
      ['model', 'assets/ashfox/models/block/ashfox_crate.json'],
      ['texture', 'assets/ashfox/textures/block/ashfox_crate.png']
    ]
  );

  const metadata = jsonFileAt(bundle, 'pack.mcmeta').data as {
    pack: Record<string, unknown>;
  };
  assert.deepEqual(metadata.pack, {
    min_format: [75, 0],
    max_format: [75, 0],
    description: 'ashfox_crate · generated by ashfox'
  });
  assert.equal('supported_formats' in metadata.pack, false);
  assert.equal('pack_format' in metadata.pack, false);

  const blockstate = jsonFileAt(
    bundle,
    'assets/ashfox/blockstates/ashfox_crate.json'
  ).data as { variants: { '': { model: string } } };
  assert.equal(blockstate.variants[''].model, 'ashfox:block/ashfox_crate');
  const model = jsonFileAt(
    bundle,
    'assets/ashfox/models/block/ashfox_crate.json'
  ).data as unknown as MinecraftJavaModel;
  assert.equal('format_version' in model, false);
  assertJavaTextureReferencesResolve(bundle, model);
}

{
  const modern = createJavaProject();
  const legacy: ProjectDocument = {
    ...modern,
    formatProfile: {
      ...modern.formatProfile,
      id: 'minecraft.java_block',
      minecraftVersion: '1.21.5',
      resourcePackFormat: 55
    }
  };
  const bundle = exportMinecraftJavaBlock(legacy);
  assertPortableBundle(bundle);
  assert.equal(bundle.target.version, '1.21.5');
  const metadata = jsonFileAt(bundle, 'pack.mcmeta').data as {
    pack: Record<string, unknown>;
  };
  assert.deepEqual(metadata.pack, {
    pack_format: 55,
    supported_formats: 55,
    description: 'ashfox_crate · generated by ashfox'
  });
  assert.equal('min_format' in metadata.pack, false);
  assert.equal('max_format' in metadata.pack, false);
}

{
  const previous = createJavaProject();
  const current: ProjectDocument = {
    ...previous,
    formatProfile: {
      ...previous.formatProfile,
      id: 'minecraft.java_block',
      minecraftVersion: '26.2',
      resourcePackFormat: 88
    }
  };
  const bundle = exportMinecraftJavaBlock(current);
  assertPortableBundle(bundle);
  assert.equal(bundle.target.version, '26.2');
  const metadata = jsonFileAt(bundle, 'pack.mcmeta').data as {
    pack: Record<string, unknown>;
  };
  assert.deepEqual(metadata.pack, {
    min_format: [88, 0],
    max_format: [88, 0],
    description: 'ashfox_crate · generated by ashfox'
  });
  assert.equal('supported_formats' in metadata.pack, false);
  assert.equal('pack_format' in metadata.pack, false);
}

{
  const project = createAnimatedBedrockProject();
  if (project.formatProfile.id !== 'minecraft.bedrock') {
    throw new Error('Bedrock fixture profile is unavailable.');
  }
  const bundle = exportMinecraftBedrock(project);
  assertPortableBundle(bundle);
  assert.equal(
    bundle.target.version,
    project.formatProfile.minecraftVersion
  );
  assert.equal(bundle.rootPath, 'bedrock-resource-pack-assets');
  assert.equal(bundle.files.some((file) => file.role === 'manifest'), false);
  const geometry = jsonFileAt(
    bundle,
    'models/blocks/ashfox_crate.geo.json'
  ).data as { format_version: string };
  const animation = jsonFileAt(
    bundle,
    'animations/ashfox_crate.animation.json'
  ).data as { format_version: string };
  assert.equal(geometry.format_version, '1.21.0');
  assert.equal(animation.format_version, '1.8.0');
}

{
  const project = createGeckoLib5Project();
  const bundle = exportGeckoLib5(project);
  assertPortableBundle(bundle);
  assert.equal(bundle.target.version, '1.21.11');
  assert.equal(bundle.rootPath, 'src/main/resources');
  assert.deepEqual(bundle.entrypoints, [
    'assets/ashfox/geckolib/models/block/ashfox_crate.geo.json',
    'assets/ashfox/geckolib/animations/block/ashfox_crate.animation.json'
  ]);
  const geometry = jsonFileAt(bundle, bundle.entrypoints[0]).data as {
    format_version: string;
  };
  const animation = jsonFileAt(bundle, bundle.entrypoints[1]).data as {
    format_version: string;
  };
  assert.equal(
    geometry.format_version,
    '1.12.0'
  );
  assert.equal(animation.format_version, '1.8.0');
}
